import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import NavLeftSide from "@/components/layout/NavLeftSide";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ background: "#F8FAFD" }} className={poppins.className}>
        <NavBar />
        <div className="flex">
          <NavLeftSide />
          {children}
        </div>
      </body>
    </html>
  );
}
